// GitHub 仓库数据
const reposData = [
    // Python 学习
    {
        name: "jackfrued/Python-100-Days",
        title: "Python - 100天从新手到大师",
        github: "https://github.com/jackfrued/Python-100-Days",
        author: "jackfrued",
        stars: "179.8k",
        forks: "55.5k",
        updated: "2026年02月25日",
        category: "python",
        categoryName: "🐍 Python 学习",
        comment: "最受欢迎的中文 Python 入门教程，学习路线清晰，从基础到项目实战全覆盖。适合零基础系统学习。",
        intro: "Python - 100天从新手到大师"
    },
    {
        name: "walter201230/Python",
        title: "最良心的 Python 教程",
        github: "https://github.com/walter201230/Python",
        website: "https://www.readwithu.com",
        author: "walter201230",
        stars: "25.5k",
        forks: "5.5k",
        updated: "2023年10月23日",
        category: "python",
        categoryName: "🐍 Python 学习",
        comment: "内容良心但更新较慢（6年前），可作为入门参考，建议结合较新资料学习。",
        intro: "最良心的 Python 教程"
    },
    {
        name: "trekhleb/learn-python",
        title: "📚 Playground and cheatsheet for learning Python",
        github: "https://github.com/trekhleb/learn-python",
        author: "trekhleb",
        stars: "17.8k",
        forks: "2.9k",
        updated: "2025年11月23日",
        category: "python",
        categoryName: "🐍 Python 学习",
        comment: "按主题分类的 Python 代码示例集合，非常适合做速查表和练习参考。",
        intro: "📚 Playground and cheatsheet for learning Python. Collection of Python scripts that are split by topics and contain code examples with explanations."
    },
    {
        name: "iswbm/python-guide",
        title: "Python中文指南：从零到一的零基础 Python 教程",
        github: "https://github.com/iswbm/python-guide",
        website: "http://python.iswbm.com",
        author: "iswbm",
        stars: "392",
        forks: "115",
        updated: "2026年01月26日",
        category: "python",
        categoryName: "🐍 Python 学习",
        comment: "中文 Python 指南，适合零基础入门，有在线文档可读。",
        intro: "Python中文指南：从零到一的零基础 Python 教程"
    },
    {
        name: "codebasics/py",
        title: "Repository to store sample python programs for python learning",
        github: "https://github.com/codebasics/py",
        author: "codebasics",
        stars: "7.3k",
        forks: "16.9k",
        updated: "2025年07月24日",
        category: "python",
        categoryName: "🐍 Python 学习",
        comment: "包含 NumPy、Pandas 等热门库的教程，以 Jupyter Notebook 形式呈现。",
        intro: "Repository to store sample python programs for python learning"
    },
    {
        name: "Jack-Cherish/PythonPark",
        title: "Python 开源项目之「自学编程之路」",
        github: "https://github.com/Jack-Cherish/PythonPark",
        author: "Jack-Cherish",
        stars: "11.3k",
        forks: "1.7k",
        updated: "2024年11月26日",
        category: "python",
        categoryName: "🐍 Python 学习",
        comment: "保姆级教程，涵盖 AI 实验室、数据结构、机器学习实战、网络爬虫、大厂面经等。",
        intro: "Python 开源项目之「自学编程之路」，保姆级教程：AI实验室、宝藏视频、数据结构、学习指南、机器学习实战、深度学习实战、网络爬虫、大厂面经、程序人生、资源分享。"
    },
    {
        name: "Jack-Cherish/python-spider",
        title: "🌈Python3网络爬虫实战",
        github: "https://github.com/Jack-Cherish/python-spider",
        website: "https://cuijiahua.com/blog/spider/",
        author: "Jack-Cherish",
        stars: "19.5k",
        forks: "6.0k",
        updated: "2024年08月19日",
        category: "python",
        categoryName: "🐍 Python 学习",
        comment: "实战项目丰富，涵盖淘宝、京东、网易云、B站、12306、抖音等爬虫案例。",
        intro: ":rainbow:Python3网络爬虫实战：淘宝、京东、网易云、B站、12306、抖音、笔趣阁、漫画小说下载、音乐电影下载等"
    },
    {
        name: "jobbole/awesome-python-cn",
        title: "Python资源大全中文版",
        github: "https://github.com/jobbole/awesome-python-cn",
        website: "http://jobbole.github.io/awesome-python-cn/",
        author: "jobbole",
        stars: "30.3k",
        forks: "8.0k",
        updated: "2022年08月29日",
        category: "python",
        categoryName: "🐍 Python 学习",
        comment: "Python 生态资源汇总，但 5 年未更新，部分内容可能过时。",
        intro: "Python资源大全中文版，包括：Web框架、网络爬虫、模板引擎、数据库、数据可视化、图片处理等，由「开源前哨」和「Python开发者」微信公号团队维护更新。"
    },
    {
        name: "d2l-ai/d2l-zh",
        title: "《动手学深度学习》：面向中文读者、能运行、可讨论",
        github: "https://github.com/d2l-ai/d2l-zh",
        website: "http://zh.d2l.ai",
        author: "d2l-ai",
        stars: "76.3k",
        forks: "12.2k",
        updated: "2024年07月30日",
        category: "python",
        categoryName: "🐍 Python 学习",
        comment: "李沐老师经典教程，被 60 国 400 所大学采用，深度学习必读。",
        intro: "《动手学深度学习》：面向中文读者、能运行、可讨论。中英文版被70多个国家的500多所大学用于教学。"
    },

    // Java 学习
    {
        name: "itwanger/toBeBetterJavaer",
        title: "一份通俗易懂、风趣幽默的 Java 学习指南",
        github: "https://github.com/itwanger/toBeBetterJavaer",
        website: "https://javabetter.cn",
        author: "itwanger",
        stars: "16.8k",
        forks: "2.3k",
        updated: "2026年03月20日",
        category: "java",
        categoryName: "☕ Java 学习",
        comment: "二哥的 Java 进阶之路，内容风趣幽默，涵盖基础、并发、JVM、企业开发、面试等。",
        intro: "一份通俗易懂、风趣幽默的Java学习指南，内容涵盖Java基础、Java并发编程、Java虚拟机、Java企业级开发、Java面试等核心知识点。学Java，就认准二哥的Java进阶之路😄"
    },
    {
        name: "hollischuang/toBeTopJavaer",
        title: "To Be Top Javaer - Java工程师成神之路",
        github: "https://github.com/hollischuang/toBeTopJavaer",
        website: "https://www.hollischuang.com",
        author: "hollischuang",
        stars: "25.5k",
        forks: "5.4k",
        updated: "2024年01月03日",
        category: "java",
        categoryName: "☕ Java 学习",
        comment: "Java 工程师进阶经典，体系完整，适合有一定基础后深入学习。",
        intro: "To Be Top Javaer - Java工程师成神之路"
    },
    {
        name: "fuzhengwei/CodeGuide",
        title: "小傅哥的 Java 学习历程技术汇总",
        github: "https://github.com/fuzhengwei/CodeGuide",
        website: "https://bugstack.cn",
        author: "fuzhengwei",
        stars: "45.2k",
        forks: "6.2k",
        updated: "2026年03月19日",
        category: "java",
        categoryName: "☕ Java 学习",
        comment: "一线互联网 Java 开发经验总结，侧重 Java 核心内容，质量很高。",
        intro: ":books: 本代码库是作者小傅哥多年从事一线互联网 Java 开发的学习历程技术汇总，旨在为大家提供一个清晰详细的学习教程，侧重点更倾向编写Java核心内容。"
    },

    // AI / LLM
    {
        name: "WangRongsheng/awesome-LLM-resources",
        title: "🧑‍🚀 全世界最好的LLM资料总结",
        github: "https://github.com/WangRongsheng/awesome-LLM-resources",
        author: "WangRongsheng",
        stars: "7.8k",
        forks: "759",
        updated: "2026年03月20日",
        category: "ai",
        categoryName: "🤖 AI / LLM / 大模型",
        comment: "LLM 资料汇总全面，涵盖多模态生成、Agent、RAG、MCP 等热门方向。",
        intro: "🧑‍🚀 全世界最好的LLM资料总结（多模态生成、Agent、辅助编程、AI审稿、数据处理、模型训练、模型推理、o1 模型、MCP、小语言模型、视觉语言模型）"
    },
    {
        name: "LlamaFamily/Llama-Chinese",
        title: "Llama 中文社区",
        github: "https://github.com/LlamaFamily/Llama-Chinese",
        author: "LlamaFamily",
        stars: "14.6k",
        forks: "1.5k",
        updated: "2025年04月06日",
        category: "ai",
        categoryName: "🤖 AI / LLM / 大模型",
        comment: "中文 Llama 大模型开源生态，完全开源可商用，资料实时更新。",
        intro: "Llama中文社区，实时汇总最新Llama学习资料，构建最好的中文Llama大模型开源生态，完全开源可商用"
    },
    {
        name: "liyupi/ai-guide",
        title: "程序员鱼皮的 AI 资源大全",
        github: "https://github.com/liyupi/ai-guide",
        website: "https://ai.codefather.cn",
        author: "liyupi",
        stars: "22.5k",
        forks: "1.6k",
        updated: "2026年03月20日",
        category: "ai",
        categoryName: "🤖 AI / LLM / 大模型",
        comment: "AI 资源导航，涵盖大模型选择、Prompt 技巧、AI 编程工具（Cursor、Claude Code 等）、开发框架（Spring AI、LangChain）。",
        intro: "程序员鱼皮的 AI 资源大全 + Vibe Coding 零基础教程，分享 OpenClaw 保姆级教程、大模型玩法（DeepSeek / GPT / Gemini / Claude）、最新 AI 资讯、Prompt 提示词大全、AI 知识百科、AI 编程教程、AI 工具用法、AI 开发框架教程、AI 产品变现指南"
    },
    {
        name: "datawhalechina/llm-universe",
        title: "面向小白开发者的大模型应用开发教程",
        github: "https://github.com/datawhalechina/llm-universe",
        website: "https://datawhalechina.github.io/llm-universe/",
        author: "datawhalechina",
        stars: "11.1k",
        forks: "1.7k",
        updated: "2026年02月24日",
        category: "ai",
        categoryName: "🤖 AI / LLM / 大模型",
        comment: "适合小白快速入门 LLM 开发，搭建 Demo 项目。",
        intro: "本项目是一个面向小白开发者的大模型应用开发教程"
    },
    {
        name: "datawhalechina/self-llm",
        title: "《开源大模型食用指南》",
        github: "https://github.com/datawhalechina/self-llm",
        author: "datawhalechina",
        stars: "26.7k",
        forks: "3.4k",
        updated: "2026年03月08日",
        category: "ai",
        categoryName: "🤖 AI / LLM / 大模型",
        comment: "针对中国开发者的大模型微调、部署教程，基于 Linux 环境，非常实用。",
        intro: "《开源大模型食用指南》针对中国宝宝量身打造的基于Linux环境快速微调（全参数/Lora）、部署国内外开源大模型（LLM）/多模态大模型（MLLM）教程"
    },
    {
        name: "microsoft/ai-agents-for-beginners",
        title: "12 Lessons to Get Started Building AI Agents",
        github: "https://github.com/microsoft/ai-agents-for-beginners",
        author: "microsoft",
        stars: "47.2k",
        forks: "7.8k",
        updated: "2026年03月19日",
        category: "ai",
        categoryName: "🤖 AI / LLM / 大模型",
        comment: "微软出品的 AI Agent 入门课程，英文但质量极高。",
        intro: "12 Lessons to Get Started Building AI Agents"
    },

    // 算法
    {
        name: "krahets/hello-algo",
        title: "《Hello 算法》：动画图解、一键运行的数据结构与算法教程",
        github: "https://github.com/krahets/hello-algo",
        website: "https://www.hello-algo.com",
        author: "krahets",
        stars: "123.5k",
        forks: "14.9k",
        updated: "2026年01月23日",
        category: "algorithm",
        categoryName: "📊 算法与数据结构",
        comment: "真正的"破圈"级项目！动画图解 + 多语言代码实现，算法学习首选。",
        intro: "《Hello 算法》：动画图解、一键运行的数据结构与算法教程。支持简中、繁中、English、日本語，提供 Python, Java, C++, C, C#, JS, Go, Swift, Rust, Ruby, Kotlin, TS, Dart 等代码实现"
    },

    // 前端
    {
        name: "qianguyihao/Web",
        title: "千古前端图文教程",
        github: "https://github.com/qianguyihao/Web",
        website: "https://web.qianguyihao.com",
        author: "qianguyihao",
        stars: "28.5k",
        forks: "6.3k",
        updated: "2025年12月08日",
        category: "frontend",
        categoryName: "🌐 前端学习",
        comment: "超详细的前端入门到进阶知识库，从零开始学前端。",
        intro: "千古前端图文教程，超详细的前端入门到进阶知识库。从零开始学前端，做一名精致优雅的前端工程师。"
    },
    {
        name: "ruanyf/es6tutorial",
        title: "《ECMAScript 6 入门》",
        github: "https://github.com/ruanyf/es6tutorial",
        author: "ruanyf",
        stars: "20.3k",
        forks: "4.1k",
        updated: "2026年03月12日",
        category: "frontend",
        categoryName: "🌐 前端学习",
        comment: "阮一峰老师的 ES6 经典教程，前端开发者必读。",
        intro: "《ECMAScript 6入门》是一本开源的 JavaScript 语言教程，全面介绍 ECMAScript 6 新增的语法特性。"
    },
    {
        name: "PanJiaChen/vue-element-admin",
        title: "基于 Vue 的后台管理系统",
        github: "https://github.com/PanJiaChen/vue-element-admin",
        website: "https://panjiachen.github.io/vue-element-admin",
        author: "PanJiaChen",
        stars: "78.5k",
        forks: "25.7k",
        updated: "2024年10月24日",
        category: "frontend",
        categoryName: "🌐 前端学习",
        comment: "Vue 后台管理经典项目，功能完善，文档齐全。",
        intro: "Vue 后台管理经典项目"
    },

    // 后端
    {
        name: "qiurunze123/miaosha",
        title: "秒杀系统设计与实现",
        github: "https://github.com/qiurunze123/miaosha",
        author: "qiurunze123",
        stars: "26.6k",
        forks: "6.6k",
        updated: "2025年04月18日",
        category: "backend",
        categoryName: "🖥️ 后端 / 系统设计",
        comment: "互联网工程师进阶经典，高并发系统设计必看。",
        intro: "⭐⭐⭐⭐秒杀系统设计与实现.互联网工程师进阶与分析"
    },

    // 小程序
    {
        name: "dcloudio/uni-app",
        title: "使用 Vue 语法开发小程序、H5、App 的统一框架",
        github: "https://github.com/dcloudio/uni-app",
        website: "https://uniapp.dcloud.net.cn/",
        author: "dcloudio",
        stars: "33.6k",
        forks: "8.0k",
        updated: "2026年03月20日",
        category: "weapp",
        categoryName: "📱 微信小程序 / uni-app",
        comment: "跨平台开发首选，一套代码多端运行。",
        intro: "使用 Vue 语法开发小程序、H5、App 的统一框架"
    },
    {
        name: "NervJS/taro",
        title: "开放式跨端跨框架解决方案",
        github: "https://github.com/NervJS/taro",
        website: "https://taro.zone/",
        author: "NervJS",
        stars: "29.7k",
        forks: "3.3k",
        updated: "2026年03月20日",
        category: "weapp",
        categoryName: "📱 微信小程序 / uni-app",
        comment: "支持 React/Vue/Nerv 开发多端应用，京东出品。",
        intro: "开放式跨端跨框架解决方案，支持使用 React/Vue 等框架来开发微信/京东/百度/支付宝/字节跳动/QQ/快手小程序/H5 等应用。"
    },
    {
        name: "justjavac/awesome-wechat-weapp",
        title: "微信小程序开发资源汇总",
        github: "https://github.com/justjavac/awesome-wechat-weapp",
        author: "justjavac",
        stars: "36.1k",
        forks: "5.7k",
        updated: "2025年11月19日",
        category: "weapp",
        categoryName: "📱 微信小程序 / uni-app",
        comment: "微信小程序开发资源大全，必收藏。",
        intro: "微信小程序开发资源汇总"
    },

    // macOS
    {
        name: "herrbischoff/awesome-macos-command-line",
        title: "超棒的 macOS 命令行工具",
        github: "https://github.com/herrbischoff/awesome-macos-command-line",
        author: "herrbischoff",
        stars: "29.3k",
        forks: "1.6k",
        updated: "2026年03月04日",
        category: "macos",
        categoryName: "🍎 macOS 相关",
        comment: "近 3 万 Star 的 macOS 命令行工具集，英文文档。",
        intro: "超棒的 macOS 命令行工具"
    },
    {
        name: "tisfeng/Easydict",
        title: "简洁优雅的词典翻译 macOS App",
        github: "https://github.com/tisfeng/Easydict",
        author: "tisfeng",
        stars: "8.3k",
        forks: "487",
        updated: "2026年03月20日",
        category: "macos",
        categoryName: "🍎 macOS 相关",
        comment: "开箱即用，支持离线 OCR、有道、苹果词典、OpenAI、DeepL、Google 等翻译源。",
        intro: "简洁优雅的词典翻译 macOS App"
    },
    {
        name: "qianguyihao/Mac-list",
        title: "Mac 软件清单、使用技巧整理",
        github: "https://github.com/qianguyihao/Mac-list",
        author: "qianguyihao",
        stars: "9.8k",
        forks: "1.3k",
        updated: "2026年01月05日",
        category: "macos",
        categoryName: "🍎 macOS 相关",
        comment: "2024年2月更新，包含软件推荐和使用技巧。",
        intro: "Mac 软件清单、使用技巧整理"
    },

    // 其他精选
    {
        name: "GitHubDaily/GitHubDaily",
        title: "坚持分享 GitHub 上高质量开源项目",
        github: "https://github.com/GitHubDaily/GitHubDaily",
        author: "GitHubDaily",
        stars: "45.7k",
        forks: "4.6k",
        updated: "2025年12月31日",
        category: "other",
        categoryName: "📚 综合资源",
        comment: "每日更新优质开源项目，发现好工具的首选。",
        intro: "坚持分享 GitHub 上高质量、有趣实用的开源技术教程、开发者工具、编程网站、技术资讯。"
    },
    {
        name: "Anduin2017/HowToCook",
        title: "程序员在家做饭方法指南",
        github: "https://github.com/Anduin2017/HowToCook",
        author: "Anduin2017",
        stars: "47.2k",
        forks: "6.3k",
        updated: "2026年03月19日",
        category: "other",
        categoryName: "🔧 开发工具 / 其他",
        comment: "程序员做饭指南，有趣的跨界项目，中文 only。",
        intro: "程序员在家做饭方法指南。Programmer's guide about how to cook at home."
    },
    {
        name: "ruanyf/weekly",
        title: "科技爱好者周刊",
        github: "https://github.com/ruanyf/weekly",
        author: "ruanyf",
        stars: "26.6k",
        forks: "3.1k",
        updated: "2026年03月20日",
        category: "other",
        categoryName: "📚 综合资源",
        comment: "每周五发布，了解科技资讯的好渠道。",
        intro: "科技爱好者周刊，每周五发布"
    },
    {
        name: "1c7/chinese-independent-developer",
        title: "中国独立开发者项目列表",
        github: "https://github.com/1c7/chinese-independent-developer",
        author: "1c7",
        stars: "18.3k",
        forks: "2.2k",
        updated: "2026年03月19日",
        category: "other",
        categoryName: "🔧 开发工具 / 其他",
        comment: "分享中国独立开发者正在做的项目，寻找灵感的好地方。",
        intro: "👩🏿‍💻👨🏾‍💻👩🏼‍💻👨🏽‍💻👩🏻‍💻中国独立开发者项目列表 -- 分享大家都在做什么"
    }
];
